dimension: 2

simulation:
  L: 10.0
  N: 129
  alpha: 1.0
  dt: 0.001
  steps: 500

initial_condition:
  type: gaussian_bump
  center: 0.0
  width: 0.5
  amplitude: 1.0

output:
  folder: figures
  plot_profile: true
  save_animation: true
  save_diagnostics: true