grid:
  L: 10.0
  N: 129

time:
  dt: 0.001
  steps: 500

pde:
  type: heat 
  dimension: 2    
  alpha: 1.0       
  beta: 5.0           
  nu: 0.1              

integrator:
  method: rk4           

initial_condition:
  type: gaussian_bump
  center: 0.0
  width: 0.5
  amplitude: 1.0

output:
  folder: figures
  plot_profile: true
  save_animation: true
  save_diagnostics: true

validation:
  check_stability: true